### ISSUE TITLE
raise KeyError(key) from err KeyError: '1000g_AF'

### ISSUE THREAD

**Issue by halessi** [bio-ontology-research-group/DeepSVP#2]
Hi, am back after calling and annotating CNV. 

When running DeepSVP now, I get to 75% and immediately crash to this traceback: 

Traceback (most recent call last):
  File "/Users/alessihd/opt/miniconda3/envs/py36/bin/deepsvp", line 8, in <module>
    sys.exit(main())
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/deepsvp/main.py", line 119, in main
    maf_filter)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/deepsvp/main.py", line 290, in func_wrapper
    value = func(*args, **kwargs)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/deepsvp/main.py", line 460, in load_cnv_model
    data['1000g_AF'].fillna(0, inplace=True)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: '1000g_AF'

This seems to be because my annotated output has no 1000g_AF column. Unfortunately, after further diving into the DeepSVP codebase, almost none of the columns (i.e., NumPromoters, TriS_CGscore) match up with what came from the AnnotSV annotation.

Has AnnotSV changed their labels? Any ideas would be appreciated. Thanks!

**Comment by azzatha** [comment]
Hi @halessi 

Thank you so much for testing our tool!

Yes, this is because the AnnotSV updated the annotations, we used (AnnotSV 2.3) could you please try to use this version or (v2.2)? We will work on updating the data and the tool according to the updated version of AnnotSV and will let you know once we release the updated version.

Please let me know if you face any other issues or you have any questions.
